### ISSUE TITLE
[Bug] Server installer crashes with invalid parameters

### ISSUE THREAD

**Issue by Grolimo** [FTBTeam/FTB-App#113]
**Operating System:**
OS:Ubuntu 18.04 LTS SERVER

**Installer Version:**
Installer: serverinstall_31_47

**App Version:**
App: 1.0.8

**UI Version:**
UI: fa03e62e

**Log Files:**
Put links to your logs here
Not applicable, not an app issue, server installer issues.

**Describe the bug**

2 bugs actually.

1). Put anything on the CLI as parameter that is not one of the documented ones and it crashes.

2). It installs files outside the designated directory with --path.

**To Reproduce**
Steps to reproduce the behaviour:
1.  sudo serverinstall_31_47 --path /opt/ftb
No errors, the only problem is that the installer is polluting the file system by downloading and installing jar files all over the place.

**Expected behaviour**
All files to be downloaded/installed in /opt/ftb as instructed by the command line parameter.

**Screenshots**
n/a

**Additional context**

In an isolated environment (sandbox) it can be shown to download/install files in places that it should not access at all.
As it is instructed to install to /opt/ftb it should *only* access that folder to install to and nowhere else.

There is absolutely *zero* need to make a large obfuscated binary blob executable for the simple task of downloading and copying files to a folder.
A bash shell script of 5 lines and a text file containing the list of file names, where to download them from and to is all that is needed for an installer.

**Comment by CH-Paul-T** [comment]
Fixed the args in development (doesn't crash because of extra args, crashes because of missing required args, but doesn't make that clear)

Cannot reproduce the file issue, all instance-related files (excluding the logs from the actual installer) are inside the directory I specified in testing in build 13c20a7, please provide the build number, logs and information on which files.

**Comment by jikuja** [comment]
I think forge installation log might be placed in the directory where yo urun installed. I did not found any other files from output of strace.

**Comment by Grolimo** [comment]
for testing what i did is download the server installer file to my user home folder under downloads.
from there i granted execution rights.
then i executed with (direwolf20 pack) --path /opt/ftb.
Most of the files end up indeed in /opt/ftb
but it is also downloading/generating/unpacking server .jar files in ~/. and ~/Downloads/.
That should never happen.

**Comment by Grolimo** [comment]
if there do exist specific logfiles that i should get, please indicate which ones and where they would be located (/var/log/?) i still have the malware test sandbox that i used for this.

**Comment by Cloudhunter** [comment]
All logs that we create ourselves are confined to stdout. The forge installer will create a log in the working directory.

May I ask exactly what files are being placed where? Having a look at the code, I can't see anything obvious, but I would really like to get to the bottom of this.

**Comment by Grolimo** [comment]
In the folder that the installer file is in, at the end i have:
downloader.log
downloader.log.lck
forge-1.12.2-14.23.5.2847-installer.jar.log
forge-1.12.2-14.23.5.2847-universal.jar
minecraft_server.1.12.2.jar

I have attached the list of files that ends up correctly in /opt/ftb as instructed.

[files.txt](https://github.com/FTBTeam/FTB-App/files/4530505/files.txt)

Kind Regards,
Marco.

**Comment by Cloudhunter** [comment]
Seems I missed the download log whilst looking in the code - d'oh!

Can you provide the build number please?

**Comment by Cloudhunter** [comment]
Accidental close.

**Comment by Grolimo** [comment]
The build number is 13c20a7

**Comment by Grolimo** [comment]
I have written an alternative installer in Python which should work on any Linux distribution.
I have found that the cause of the problem is that the part of the java installer that runs the forge installer jar file forgets to set the working directory for the external process.
Therefore it executes with the "current" directory as environment, causing the installer to emit files there instead of into the target directory.

**Comment by Grolimo** [comment]
Also i found that if you run the installer from the same directory as you're installing to (which is not so obvious always) then it seems to download and work properly, but the server still won't work, because of some reason the eula.txt file doesn't get generated, and even if you manually create it, the forge server wrapper seems to have a problem and crashes immediately.

**Comment by Gaz492** [comment]
Hi,

Does this issue still happen for you?
If you do still have the issue are you able to provide the output of the server installer so we can take a look at this.
