### ISSUE TITLE
[Bug (Windows)] App fails to proceed past splash screen

### ISSUE THREAD

**Issue by lifebound** [FTBTeam/FTB-App#402]
**Operating System:**
OS: Win 10 Version Dev (OS Build 21327.1010)

**App Version:**
App: 1.21.13.1631

**UI Version:**
UI: N/A

**Log Files:**
ftbapp.log: https://pste.ch/osiquhahus
background.html.log: https://pste.ch/oxohekonoc
Other logs can be provided on request

** Debug Code: **
FTB Debug Code: FTB-DBGALALAWALIH

**Describe the bug**
The FTB App fails to proceed past the splash screen. This appears to be due to an unexpected fault in background.html:

```
2021-03-18 07:57:04,033 (INFO) </dist/background/main.js> (:24) - java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unmapped relationship: 7

2021-03-18 07:57:04,034 (INFO) </dist/background/main.js> (:24) - 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)

2021-03-18 07:57:04,035 (INFO) </dist/background/main.js> (:24) - 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)

2021-03-18 07:57:04,036 (INFO) </dist/background/main.js> (:24) - 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)

2021-03-18 07:57:04,037 (INFO) </dist/background/main.js> (:24) - 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)

2021-03-18 07:57:04,038 (INFO) </dist/background/main.js> (:24) - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)

2021-03-18 07:57:04,039 (INFO) </dist/background/main.js> (:24) - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)

2021-03-18 07:57:04,041 (INFO) </dist/background/main.js> (:24) - 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)

2021-03-18 07:57:04,042 (INFO) </dist/background/main.js> (:24) - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)

2021-03-18 07:57:04,043 (INFO) </dist/background/main.js> (:24) - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

2021-03-18 07:57:04,044 (INFO) </dist/background/main.js> (:24) - Caused by: java.lang.IllegalStateException: Unmapped relationship: 7

2021-03-18 07:57:04,045 (INFO) </dist/background/main.js> (:24) - 	at com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer(WinNT.java:2999)

2021-03-18 07:57:04,046 (INFO) </dist/background/main.js> (:24) - 	at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx(Kernel32Util.java:715)

2021-03-18 07:57:04,047 (INFO) </dist/background/main.js> (:24) - 	at oshi.hardware.platform.windows.WindowsCentralProcessor.getLogicalProcessorInformationEx(WindowsCentralProcessor.java:315)

2021-03-18 07:57:04,048 (INFO) </dist/background/main.js> (:24) - 	at oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:305)

2021-03-18 07:57:04,049 (INFO) </dist/background/main.js> (:24) - 	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:69)

2021-03-18 07:57:04,050 (INFO) </dist/background/main.js> (:24) - 	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:70)

2021-03-18 07:57:04,052 (INFO) </dist/background/main.js> (:24) - 	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:60)

2021-03-18 07:57:04,052 (INFO) </dist/background/main.js> (:24) - 	at oshi.util.Memoizer$1.get(Memoizer.java:84)

2021-03-18 07:57:04,053 (INFO) </dist/background/main.js> (:24) - 	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:63)

2021-03-18 07:57:04,054 (INFO) </dist/background/main.js> (:24) - 	at net.creeperhost.creeperlauncher.api.data.other.SettingsInfoData$Reply.<init>(SettingsInfoData.java:21)

2021-03-18 07:57:04,055 (INFO) </dist/background/main.js> (:24) - 	at net.creeperhost.creeperlauncher.api.handlers.other.SettingsInfoHandler.handle(SettingsInfoHandler.java:15)

2021-03-18 07:57:04,056 (INFO) </dist/background/main.js> (:24) - 	at net.creeperhost.creeperlauncher.api.handlers.other.SettingsInfoHandler.handle(SettingsInfoHandler.java:9)

2021-03-18 07:57:04,057 (INFO) </dist/background/main.js> (:24) - 	at net.creeperhost.creeperlauncher.api.handlers.IMessageHandler.handle(IMessageHandler.java:10)

2021-03-18 07:57:04,058 (INFO) </dist/background/main.js> (:24) - 	at net.creeperhost.creeperlauncher.api.WebSocketMessengerHandler.lambda$handleMessage$0(WebSocketMessengerHandler.java:126)

2021-03-18 07:57:04,059 (INFO) </dist/background/main.js> (:24) - 	... 7 more
```

However, A) I have no idea what's causing this "unmapped relationship", B) There's no indication to the user that this is happening 

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch FTB App
2. Watch as splash screen saturation cycles between full saturation and no saturation.

**Expected behaviour**
the App proceeds past the splash and I get to actually play minecraft.

**Comment by dshadowwolf** [comment]
I am seeing this exact issue - this set of errors, from what the logs show, seem to indicate something has changed in the CreeperHost API that the app is not handling properly.

**Comment by sammarks** [comment]
This actually appears to be an issue with a change introduced in the latest Windows Insider builds. If you look far enough down in the stacktrace, it looks like it starts with the `oshi` library.

Here's the related issue at oshi: https://github.com/oshi/oshi/issues/1554

And here's the PR (that they've already merged) for that related issue: https://github.com/oshi/oshi/pull/1566

Looks like you just need to update your `oshi` dependency and release a new version, and this should be fixed for Insider builds.

**Comment by robinvalk** [comment]
I'm having the same issue, where can I find the dev builds? (If they are available)

**Comment by ThePaul-T** [comment]
Unfortunately, they are not as there is no system in place for non-release Overwolf builds at Overwolfs end(Yet, we're promised it's coming). We will try and get this fix rolled out this coming week as it seems to be impacting a fair few people.

**Comment by robinvalk** [comment]
Thanks @ThePaul-T!  In the meantime I could at least play with some friends using the MultiMC 5 app.

**Comment by AmadeusWolf** [comment]
any fix for this yet? same issue still occurs on the latest insider build of windows

**Comment by rhyser9** [comment]
Still encountering this issue. Log file from .ftba/logs directory: https://pste.ch/ikevaropah

OS: Windows 10 Education Dev (OS Build 21390.2025)
App Version: 1.21.63.1928
FTB Debug Code: FTB-DBGADICOGUQAF

**Comment by rhyser9** [comment]
(Note: I don't necessarily know what I'm talking about, so take anything I say with a grain of salt... Apologies if I'm blatantly wrong regarding something.)

Per Paul_T on Discord on 06/24/2021, "I know we already updated to the latest available version of OSHI in the last update, if that hasn't fixed it we'll need to dig deeper, so copies of logs etc are still important.".

Looking at the archive for app version 1.21.701.1746, it does appears to include OSHI v5.7.0 as stated, which should fix this. The OSHI PR mentioned above was actually reverted and replaced by a version bump from JNA v5.7.0 to JNA v5.8.0 in oshi/oshi#1576 (which was still included in OSHI v5.6.1). The upstream JNA fix in question was applied in PR java-native-access/jna#1327.

However, it appears that the FTB-App archive does not include JNA v5.8.0, instead the archive contains JNA v5.5.0, so the upstream fix for this issue isn't actually present despite updating OSHI.

**Comment by dshadowwolf** [comment]
Alright. Windows 11 Preview, as far as I'm aware the latest versions of the FTB App and Overwolf, but let me do a reinstall after posting this...

Here are [the logs](https://gist.github.com/dshadowwolf/52002a9817d0b551ff6b75ce19b23ddb) -- both the `latest.log` and the `debug.log` from my last attempt to start the app.

**Comment by MichaelHillcox** [comment]
Closing as we don't support windows 11 insider right now. We have fixed the issue internally though :+1: should have a fix released soon.
