### ISSUE TITLE
Failed to log in: the authentication server are currently not reachable (StoneBlock 3)

### ISSUE THREAD

**Issue by 0Funky** [FTBTeam/FTB-App#904]
### What Operating System

Windows 10

### Debug Code

FTB-DBGOBODIYAXUW

### Describe the bug

only in the app FTB will stoneblock 3 not be able to log me into any servers and show me this error message

### Steps to reproduce

1. Open FTB
2. Launch Stoneblock 3
3. Join server
4. "Failed to log in: the authentication server are currently not reachable"

### Expected behaviour

on the regular launcher my account works fine and puts me in a server, though through the ftb app i recieve the error message of not being able to join the server

**Comment by UniqueSenpai** [comment]
Having same issue

**Comment by MichaelHillcox** [comment]
This should be fixed, let us know if it's not

**Comment by CrisisModel** [comment]
I am having this exact same issue on Linux. Same exact steps to reproduce, except it's with FTB Skies. I've tried numerous things and I can't make any progress with it.

**Comment by MichaelHillcox** [comment]
Try removing a mod called ftb-auxilium and see if that fixes it?

**Comment by Paxination** [comment]
I have been having the same issue.  Is ftb-auxilium a client side only mod?  I am running a stoneblock 3 server and dont want to have to explain to my friends how to modify the pack just so they can join.  Will removing it from my side prevent me from getting on the server?

**Comment by Paxination** [comment]
And removing it does nothing.  Still the same.  Normally I can get on my server after a couple tries, but since I got off an hour ago its not letting me get back on at all this time.
